name: my_trainings
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  card_swiper: ^3.0.1
  dotted_line: ^3.2.3
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  get: ^4.6.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/banners/
    - assets/icons/
    - assets/jsons/
    - assets/images/badges/
    - assets/images/user_profiles/
